name: Run Unit Test via Pytest of branch ${{github.branch}}
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]
    steps:
      #- run: echo "🐧 Running unit tests via Pytest"
      #- name: Check out repository code
        #uses: pytest --cov=myapp --cov-report=html -n auto
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }} 
      - name: Install dependencies  
        run: |  
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Test with pytest and coverage
        run: |
          pytest --cov=myapp --cov-report=html -n auto
      - run: echo "🍏 Unit tests executed with status -> ${{ job.status }}."

